apiVersion: apps/v1
kind: Deployment
metadata:
  name: appadi-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appadi-ui
  template:
    metadata:
      labels:
        app: appadi-ui
    spec:
      containers:
      - name: appadi-ui
        image: acrdevAppAdi.azurecr.io/appadi-ui:v4
        ports:
        - containerPort: 80
