apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appadi-ui-ingress
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: ui.innervoicebyaditi.online
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: appadi-ui
            port: 
              number: 80
